### ISSUE TITLE
cell(x, states[-1]) shape mismatch

### ISSUE THREAD

**Issue by ZhuFengdaaa** [ikostrikov/TensorFlow-Pointer-Networks#11]
I download the code and run it with tensorflow version 1.3.0

1. I encounter the error with: 
```
ImportError: cannot import name core_rnn_cell_impl
>>> from tensorflow.contrib.rnn.python.ops import rnn_cell_impl
```

I change the line 
```
from tensorflow.contrib.rnn.python.ops import rnn_cell_impl
```
to be 
```
from tensorflow.python.ops import rnn_cell_impl
```

2. I encounter the error with:
```
ValueError: Trying to share variable rnn/gru_cell/gates/kernel, but specified shape (64, 64) and found shape (33, 64).
```
It is because `x = rnn_cell_impl._linear([inp, attns], cell.output_size, True)` outputs the tensor has shape (32, 64) and combine the m_state shape (32, 64)

Now I don't know how to resolve this.

**Comment by ZhuFengdaaa** [comment]
The solution of changing 
```
x = rnn_cell_impl._linear([inp, attns], cell.output_size, True)
```
to be
```
x = rnn_cell_impl._linear([inp, attns], 1, True)
```
can run the code, but I don't know if it is the correct solution.

**Comment by lavafool** [comment]
Finally find out that this is because "cell.output_size" should be replaced by "input_size" which is 1 here.
See http://www.cnblogs.com/rocketfan/p/6261467.html for reference.
