### ISSUE TITLE
What does attns do?

### ISSUE THREAD

**Issue by calee88** [ikostrikov/TensorFlow-Pointer-Networks#6]
Hello.

I'm trying to understand the code.

In pointer.py, there is an attns.

It is initialized as zeros and becomes an input to _linear function.

Why do you need it?

Thanks in advance.

**Comment by chenghuige** [comment]
@calee88  actually here attns do nothing, if you just set x = input you can get similar result.
attention not used for next input concat, only used for output.

**Comment by calee88** [comment]
@chenghuige Okay. I understood. Thank you very much.
