### ISSUE TITLE
Weight Sharing

### ISSUE THREAD

**Issue by calee88** [ikostrikov/TensorFlow-Pointer-Networks#7]
Is this model supposed to share weights between encoder and decoder?

When I run the code, it shows an ValueError that I attempted to reuse RNNCell.

I can either reuse it or not, but I am not sure what approach I should take.

Thanks in advance.

**Comment by chenghuige** [comment]
@calee88  seems so,  I did experiment if not share weights, use another cell for decoder, result is similar.

**Comment by calee88** [comment]
@chenghuige Okay. I got it. Thanks.
